### ISSUE TITLE
Create a Python script that identifies the total number of students with a specific status (STU.TG) by grade (STU.GR) and by program code (STU.SP))

### ISSUE THREAD

**Issue by shwndea** [code4sac/learning-blocks#19]
- [ ] Step#1:

- Using the [Aeries API Documentation](https://support.aeries.com/support/solutions/articles/14000113683-aeries-api-student-related-end-points) use the following url to make a request:
- [https://demo.aeries.net/aeries/api/v5/schools/994/students/99400001](https://demo.aeries.net/aeries/api/v5/schools/994/students/99400001?cert=477abe9e7d27439681d62f4e0de1f5e1)
- 
- > - SchoolCode ("994")(required) – the Aeries School Code. This is normally 1-999.
- > - StudentID ("99400001")(optional) – the Aeries Student District Student ID Number.
- 
- Request the following and put them in a json and csv file locally. The header should be the code names: (format: Code Name  ->   Aeries Table.Column Name -> Description)
- > - "StudentID"  -> STU.ID  -> Student ID
- > - "Grade" -> STU.GR   -> 0-18 Student’s grade level
- > - "AttendanceProgramCodePrimary" -> STU.SP -> The primary specialized attendance program to which this student currently belongs. Attendance programs are used to separate certain students’ attendance data in the                                                                     monthly apportionment (ADA) calculations.
- > - "InactiveStatusCode"  -> STU.TG   -> Student’s status (blank is active)

Return:

> - Json File
> - CSV File
> - a table that shows the total number of student with a specific status (STU.TG) by grade (STU.GR) and by program code (STU.SP))

- [ ] Step#2

Turn that request into a pythonic method that requests for value 994 (a specific school id) and value 99400001 (student id number)

- [ ] Step#3

Using Python Method example (currently residing in "proj-learning-blocks" slack) as a guide turn that method into a class

- [ ] Future steps:

Adapt request to two more urls:

- /api/v5/schools/{SchoolCode}/students/grade/{GradeLevel}

> - SchoolCode (required) – the Aeries School Code. This is normally 1-999.
>- GradeLevel (required) – the academic grade level of the set of students to return.

/api/v5/schools/{SchoolCode}/students/sn/{StudentNumber}
> - SchoolCode (required) – the Aeries School Code. This is normally 1-999.
>- GradeLevel (required) – the academic grade level of the set of students to return.

Query String Filters:
StartingRecord – (numeric) The Record-Count value of the first record to return (inclusive).
EndingRecord – (numeric) The Record-Count value of the last record to return (inclusive).
Notes:
If Student ID is not passed, all students for the given school will be returned.
Results are always returned in the form of an "Array of Students" because often students have multiple records in a district if they are concurrently enrolled or have switched between schools during the school year.

**Comment by dainizzz** [comment]
Hi! I'm a little confused by the title of the issue; should this script return a number of students that match specific criteria as well as returning a JSON file and CSV file?

**Comment by shwndea** [comment]
My apologies the user will enter a series of id numbers and will return:

- store/return a number of student names that correspond to the id numbers in string
- store/return the program code (STU.SP)) that the students in the list have
- generate a list of total number of students by their program code (STU.SP)): X students with Program C code

Feel free to stop by a Code 4 Sac meeting to discuss more!
