### ISSUE TITLE
Add database with Postgres and SQLAlchemy

### ISSUE THREAD

**Issue by natebass** [code4sac/learning-blocks#30]
The back end without Docker needs a database to make API calls. It should be implemented with [SQLAlchemy](https://www.sqlalchemy.org/) and [PostgreSQL](https://www.postgresql.org/).

Documentation should include steps to install on Mac, Windows, Linux.

- Install Python dependencies
- Install Postgres
- Connect to [pgAdmin](https://www.pgadmin.org/)
- Run an [Alembic](https://alembic.sqlalchemy.org/en/latest/) migration
- Run the front end and back end simultaneously
- Connect to the back end from the front end site
--Status--
- [x]  add to no-docker version
- [ ]  add to docker version

**Comment by natebass** [comment]
This is done and documented, for the most part, in the no Docker version. MacOS instructions are one improvement that hasn't be added.

**Comment by shwndea** [comment]
- [ ] add to docker version
