### ISSUE TITLE
Get and Post API Requests to Canvas

### ISSUE THREAD

**Issue by shwndea** [code4sac/learning-blocks#31]
Using the Canvas API request documentation:
https://community.canvaslms.com/t5/Community-Hub/Awesome-CanvasLMS/ba-p/259722#CanvasAPI
https://community.canvaslms.com/t5/Canvas-Developers-Group/A-Simple-Python-GET-Script/ba-p/273742
https://canvas.instructure.com/doc/api/file.outcomes_csv.html

Write get and post documentation for Canvas urls:
Assignment
Discussion
Page
File
Folder
Quiz
Module
SessionlessLaunchUrl

Template for an api request can be found here:
https://github.com/code4sac/learning-blocks/blob/main/Stand_%20Alone_%20Python_%20Scripts/CanvasAPI.py

**Comment by jSunpayco** [comment]
Hi @shwndea! Did you envision something like this? 
https://github.com/code4sac/learning-blocks/compare/main...jSunpayco:learning-blocks:main?short_path=afeeb02#diff-afeeb021a2aa78aa11485d5fad6ac6305199f42b63ecb18e81cbe5cc2ddcf338

**Comment by natebass** [comment]
@jSunpayco That looks good. Maybe we can add a different section or file that talks about how to do it in Python.

**Comment by jSunpayco** [comment]
I forgot to mention that I created a pull request yesterday. You can find it [here](https://github.com/code4sac/learning-blocks/pull/42)

**Comment by shwndea** [comment]
- [ ] pu
