### ISSUE TITLE
Documentation on How to update Tables in the Learning-Blocks-Docker-Version

### ISSUE THREAD

**Issue by shwndea** [code4sac/learning-blocks#36]
Write documentation for how to do the following in the Learning-Blocks-Docker-Version :

- Modify or add SQLAlchemy models in `./backend/app/app/models/`, 
- Pydantic schemas in `./backend/app/app/schemas/`,
-  API endpoints in `./backend/app/app/api/`, 
- CRUD (Create, Read, Update, Delete) utils in `./backend/app/app/crud/`.
 
The easiest way might be to copy the ones for Items (models, endpoints, and CRUD utils) and update them to your needs.

Add and modify tasks to the Celery worker in `./backend/app/app/worker.py`.

**Comment by natebass** [comment]
I got the backed project initialization documented, with installation steps for Linux.

There still needs work documenting our student API specific stuff.
